version: 2
updates:
  # Go modules for proxy service
  - package-ecosystem: "gomod"
    directory: "/proxy"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"
      - "proxy"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Go modules for admin service
  - package-ecosystem: "gomod"
    directory: "/admin"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"
      - "admin"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Docker images
  - package-ecosystem: "docker"
    directory: "/proxy"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/admin"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
