name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy Registry
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            # Run deployment script
            /home/pluggedin/registry/deploy.sh
            
      - name: Verify deployment
        run: |
          # Wait a moment for deployment to complete
          sleep 10
          
          # Check if the service is responding
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://registry.plugged.in/v0/health)
          
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Deployment verified - service is healthy"
          else
            echo "❌ Deployment verification failed - HTTP $HTTP_CODE"
            exit 1
          fi
          
      - name: Notify on success
        if: success()
        run: |
          echo "🚀 Successfully deployed registry.plugged.in"
          echo "Commit: ${{ github.sha }}"
          echo "Deployed by: ${{ github.actor }}"
          
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Deployment failed for registry.plugged.in"
          echo "Commit: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"